export const Users = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    role: "influencer",
    password: "aQ123",
  },
  {
    id: 2,
    name: "admin",
    username: "admin",
    email: "admin@gmail.com",
    role: "admin",
    password: "aQ123",
  },
  {
    id: 3,
    name: "marketer",
    username: "mk",
    email: "marketer@gmail.com",
    role: "marketer",
    password: "aQ123",
  },
  {
    id: 4,
    name: "carry",
    username: "Bret",
    email: "carry@gmail.com",
    role: "influencer",
    password: "aQ123",
  },
  {
    id: 5,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    role: "influencer",
    password: "aQ123",
  },
  {
    id: 6,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    role: "influencer",
    password: "aQ123",
  },
];
    